namespace Common
{
    public enum Operation
    {
        Login,
        Kraj,
        GetCountries,
        GetPlayers,
        GetTeams,
        GetGames,
        SavePlayer,
        SaveTeam,
        SaveGame,
        SearchPlayers,
        SearchTeams,
        SearchGames,
        DeletePlayer,
        DeleteTeam,
        DeleteGame,
        UpdatePlayer,
        UpdateTeam,
        UpdateGame,
        GetStats,
        SaveFixtures,
        AddGamesSingle,
        AddGamesDouble,
        GetPositions,
    }
}
